namespace: demo-ha-app
appDeployment:
  name: demo-app    
  replicas: 2
  containers:
    image: 
      release: ahesmat/incident-api
      version: v1
    port: 
      containerPort: "80"
      name: http  
    resources: 
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
appConfigMap:
  data:
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: appdb
    DB_USER: appuser
appService:
  port: "80"
  type: ClusterIP


postgresSTS:
  name: postgres
  replicas: 1
  containers:
    port: "5432"
    release: 16
postgresSecret:
  name: postgres-secret     

  

        
