apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-ha-app
  labels:
    app: {{ .Values.appDeployment.name }}
data:
  DB_HOST: {{ .Values.appConfigMap.data.DB_HOST }}
  DB_PORT: "{{ .Values.appConfigMap.data.DB_PORT }}"
  DB_NAME: {{ .Values.appConfigMap.data.DB_NAME }}
  DB_USER: {{ .Values.appConfigMap.data.DB_USER }}
