apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appDeployment.name  }}
  namespace: demo-ha-app
  labels: 
    app: {{ .Values.appDeployment.name  }}
spec:
  replicas: {{ .Values.appDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appDeployment.name  }}
  template:
    metadata:
      labels:
        app: {{ .Values.appDeployment.name  }}
    spec:
      containers:
      - name: {{ .Values.appDeployment.name }}
        image: {{ .Values.appDeployment.containers.image.release }}:{{ .Values.appDeployment.containers.image.version }} # Replace with your actual app image
        ports:
        - containerPort: {{ .Values.appDeployment.containers.port.containerPort }}
          name: {{ .Values.appDeployment.containers.port.name }}
        resources:  
          requests:
            memory: {{ .Values.appDeployment.containers.resources.requests.memory }}
            cpu: {{ .Values.appDeployment.containers.resources.requests.cpu }}
          limits: 
            memory: {{ .Values.appDeployment.containers.resources.limits.memory }} 
            cpu: {{ .Values.appDeployment.containers.resources.limits.cpu }}         
        env:
        - name: DB_HOST # Injecting as an env var
          valueFrom:
            configMapKeyRef:
              name: app-config # Name of the ConfigMap
              key: DB_HOST  # Key from the ConfigMap
        - name: DB_PORT # Injecting another as env var
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME # Injecting as an env var
          valueFrom:
            configMapKeyRef:
              name: app-config # Name of the ConfigMap
              key: DB_NAME  # Key from the ConfigMap
        - name: DB_USER # Injecting another as env var
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD         
        livenessProbe: 
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10      #Time probe waits before start checking
          periodSeconds: 10        #Frequency of running the probe
          timeoutSeconds: 2          #number of seconds probe waits for a response
          failureThreshold: 3         # number of failures until probe starts the container
        readinessProbe:
          httpGet:      
            path: /health
            port: http
          initialDelaySeconds: 5      #Number of seconds probe waits before start checking
          periodSeconds: 5          # Frequency of probe checking for readiness
          timeoutSeconds: 2         # number of seconds probe waits for a response
          failureThreshold: 3        # number of consecutive successes to mark as ready
