apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresSecret.name }}
  namespace: demo-ha-app
type: Opaque
data:
  POSTGRES_DB: YXBwZGI=
  POSTGRES_USER: YXBwdXNlcg==
  POSTGRES_PASSWORD: ZG9sY2VBTkRnYWJiYW5hXzg3       
