apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-ha-app # Or your specific namespace
spec:
  # Defines the storage characteristics requested by the user/app
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
    # - ReadOnlyMany # Mount read-only by many nodes
    # - ReadWriteMany # Mount read-write by many nodes (if supported)
  storageClassName: manual # Links to a StorageClass for dynamic provisioning
  resources:
    requests:
      storage: 1Gi # Request 1 Gibibyte of storage

