apiVersion: v1
kind: Service
metadata:
  name: demo-app # Name of the Service
  namespace: demo-ha-app
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app # Routes traffic to pods with this label
  ports:
    - protocol: TCP
      port: 80        # Port the Service listens on
      targetPort: 80 # Port your containers are listening on
      name: http
  type: ClusterIP # Exposes service externally via cloud provider load balancer

